name: Coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7"
          architecture: x64
      - run: pip install nox==2021.6.6
      - run: pip install poetry==1.1.6
      - run: nox --sessions tests coverage
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
